### ISSUE TITLE
The page does not automatically save when refreshed

### ISSUE THREAD

**Issue by smilegodly** [Grommers00/my-note#10]
I have noticed your app has no auto-save feature , after typing some input. 

Currently you must explicitly click "save file", but if you forgot to click "save" for some reason, you lose all the input in the notepad.

I'd like to add an "auto-save" feature if it's alright with you.

Thanks,

**Comment by Grommers00** [comment]
Hi smilegodly, 

I actually removed this feature because I wasn't liking to not have the ability to choose when to restore, however I would like the ability for it to save perhaps restore something you wrote 10-20 seconds ago.  Let me know if this is do-able as an option incase you auto-delete everything.

**Comment by smilegodly** [comment]
An idea for this is to have a timer on the page saying "Auto-Save In X Seconds" , and then having it countdown for the user to 0 before the save actually occurs.

The user could visually see the timer, and the user would know that they have 20 seconds to restore to any previous state before a save happens.

This could be an option in case somebody forget to hit the save button and lost what they wrote. The ability to restore would still be there, but, it would be a 20 second restore point window you would have before a save happened, and thus, deleting that restore point.

**Comment by Grommers00** [comment]
sounds good. I like it!
